import { ArrowUpRight, ChevronRight, FileText, MoreHorizontal, Plus, Sparkles, Star, TrendingUp, WalletCards } from 'lucide-react';
import { Link } from 'wouter';
import { toast } from 'sonner';
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts';
import { useDashboard } from '@/hooks/use-finpilot';
import { ErrorBlock, LoadingBlock, PageHeader } from '@/components/finpilot-shell';
import { ValueChart } from '@/components/data-viz';

const money = (value: number, digits = 2) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: digits, maximumFractionDigits: digits }).format(value);

export default function DashboardPage() {
  const { data, isLoading, isError } = useDashboard();
  if (isLoading) return <><PageHeader eyebrow="Personal command center" title="Good morning, Alex" description="A clear view of what matters in your financial picture." /><div className="grid gap-5 md:grid-cols-2"><LoadingBlock className="h-64" /><LoadingBlock className="h-64" /></div></>;
  if (isError || !data) return <><PageHeader eyebrow="Personal command center" title="Good morning, Alex" /><ErrorBlock /></>;

  const allocation = data.holdings.map((holding) => ({ name: holding.symbol, value: holding.allocation, color: holding.color }));
  return <div className="space-y-7">
    <PageHeader eyebrow="Personal command center · Tuesday, October 8" title="Good morning, Alex" description="The market is open. Here is the signal worth your attention today." action={<Link href="/assistant" className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-bold text-primary-foreground shadow-[0_3px_0_hsl(187_43%_18%)] transition hover:-translate-y-0.5" data-testid="link-dashboard-analyst"><Sparkles className="h-3.5 w-3.5 text-accent" />Review with analyst</Link>} />

    <section className="grid gap-4 xl:grid-cols-[1.6fr_1fr_1fr]">
      <div className="relative overflow-hidden rounded-2xl bg-primary p-6 text-primary-foreground shadow-[0_12px_30px_hsl(187_63%_29%_/_0.16)] md:p-7">
        <div className="absolute -right-10 -top-16 h-48 w-48 rounded-full border-[22px] border-accent/15" /><div className="absolute -right-2 -top-8 h-28 w-28 rounded-full border border-accent/20" />
        <div className="relative"><div className="font-mono text-[10px] uppercase tracking-[0.2em] text-primary-foreground/60">Portfolio value</div><div className="mt-3 font-mono text-[34px] font-medium tracking-[-0.06em] md:text-[42px]" data-testid="text-portfolio-value">{money(data.totalValue)}</div><div className="mt-3 flex flex-wrap items-center gap-3"><span className="inline-flex items-center gap-1 rounded-full bg-[#5e9b77]/20 px-2.5 py-1 text-xs font-bold text-[#b9e4bf]" data-testid="text-day-change"><TrendingUp className="h-3.5 w-3.5" />{money(data.dayChange)} (+{data.dayPercent}%) today</span><span className="font-mono text-[10px] text-primary-foreground/45">USD · updated 2m ago</span></div></div>
        <div className="relative mt-7"><ValueChart values={data.history} compact /></div>
      </div>
      <div className="rounded-2xl border border-border bg-card p-6 transition hover:border-primary/25">
        <div className="flex items-center justify-between"><div className="font-mono text-[10px] uppercase tracking-[0.16em] text-muted-foreground">Total return</div><div className="grid h-8 w-8 place-items-center rounded-lg bg-[#eff6ee] text-[#4b8b62]"><ArrowUpRight className="h-4 w-4" /></div></div>
        <div className="mt-7 font-mono text-[29px] font-medium tracking-[-0.05em]" data-testid="text-total-gain">{money(data.totalGain)}</div><div className="mt-2 text-xs font-semibold text-[#4b8b62]">+{data.totalGainPercent}% since inception</div><div className="mt-5 border-t border-border pt-4 text-xs leading-5 text-muted-foreground">Your portfolio has outpaced its blended benchmark over the last 12 months.</div>
      </div>
      <div className="rounded-2xl border border-border bg-card p-6 transition hover:border-primary/25">
        <div className="flex items-center justify-between"><div className="font-mono text-[10px] uppercase tracking-[0.16em] text-muted-foreground">Available cash</div><div className="grid h-8 w-8 place-items-center rounded-lg bg-[#fff4d6] text-[#a87419]"><WalletCards className="h-4 w-4" /></div></div>
        <div className="mt-7 font-mono text-[29px] font-medium tracking-[-0.05em]" data-testid="text-cash-value">{money(data.cash)}</div><div className="mt-2 text-xs font-semibold text-muted-foreground">5.2% of total value</div><div className="mt-5 border-t border-border pt-4 text-xs leading-5 text-muted-foreground">Cash is shown for context only. FinPilot does not execute trades.</div>
      </div>
    </section>

    <section className="grid gap-5 xl:grid-cols-[1.55fr_1fr]">
      <div className="rounded-2xl border border-border bg-card p-5 md:p-6">
        <div className="flex items-center justify-between"><div><h2 className="text-base font-extrabold tracking-[-0.02em]">Portfolio trajectory</h2><p className="mt-1 text-xs text-muted-foreground">Growth of invested capital · last 12 months</p></div><Link href="/portfolio" className="font-mono text-[10px] font-medium uppercase tracking-[0.12em] text-primary hover:underline" data-testid="link-view-portfolio">View portfolio <ChevronRight className="inline h-3 w-3" /></Link></div>
        <div className="mt-5"><ValueChart values={data.history} /></div>
      </div>
      <div className="rounded-2xl border border-border bg-card p-5 md:p-6">
        <div className="flex items-start justify-between"><div><h2 className="text-base font-extrabold tracking-[-0.02em]">Allocation</h2><p className="mt-1 text-xs text-muted-foreground">By holding · invested value</p></div><Link href="/portfolio" className="grid h-8 w-8 place-items-center rounded-lg text-muted-foreground hover:bg-muted hover:text-primary" data-testid="link-allocation-details"><ChevronRight className="h-4 w-4" /></Link></div>
        <div className="mt-3 flex items-center gap-3"><div className="h-[142px] w-[142px] shrink-0"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={allocation} dataKey="value" nameKey="name" innerRadius={45} outerRadius={66} paddingAngle={2} stroke="none">{allocation.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie><Tooltip formatter={(value: number) => [`${value}%`, 'Allocation']} /></PieChart></ResponsiveContainer></div><div className="min-w-0 flex-1 space-y-2.5">{allocation.slice(0, 4).map((entry) => <div className="flex items-center justify-between gap-2 text-xs" key={entry.name}><span className="flex items-center gap-2 font-semibold"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: entry.color }} />{entry.name}</span><span className="font-mono text-muted-foreground">{entry.value}%</span></div>)}<div className="pt-1 text-[10px] text-muted-foreground">+ 1 more holding</div></div></div>
      </div>
    </section>

    <section className="grid gap-5 xl:grid-cols-[1.35fr_1fr]">
      <div className="rounded-2xl border border-border bg-card p-5 md:p-6"><div className="flex items-center justify-between"><div><h2 className="text-base font-extrabold tracking-[-0.02em]">Holdings at a glance</h2><p className="mt-1 text-xs text-muted-foreground">Today’s movement across your portfolio</p></div><Link href="/portfolio" className="text-xs font-bold text-primary hover:underline" data-testid="link-all-holdings">All holdings <ChevronRight className="inline h-3.5 w-3.5" /></Link></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[530px] text-left text-xs"><thead className="border-b border-border font-mono text-[10px] uppercase tracking-[0.12em] text-muted-foreground"><tr><th className="pb-3 font-medium">Holding</th><th className="pb-3 text-right font-medium">Value</th><th className="pb-3 text-right font-medium">Today</th><th className="pb-3 text-right font-medium">Weight</th></tr></thead><tbody>{data.holdings.slice(0, 4).map((holding) => <tr className="border-b border-border/60 last:border-0" key={holding.symbol} data-testid={`row-holding-${holding.symbol}`}><td className="py-3"><div className="flex items-center gap-2.5"><span className="grid h-7 w-7 place-items-center rounded-lg text-[9px] font-bold text-primary-foreground" style={{ backgroundColor: holding.color }}>{holding.symbol.slice(0, 2)}</span><div><div className="font-bold">{holding.symbol}</div><div className="max-w-[145px] truncate text-[10px] text-muted-foreground">{holding.name}</div></div></div></td><td className="text-right font-mono">{money(holding.value)}</td><td className="text-right font-mono text-[#4b8b62]">+{holding.change.toFixed(2)}%</td><td className="text-right font-mono text-muted-foreground">{holding.allocation}%</td></tr>)}</tbody></table></div></div>
      <div className="rounded-2xl border border-border bg-card p-5 md:p-6"><div className="flex items-center justify-between"><div><h2 className="text-base font-extrabold tracking-[-0.02em]">Market pulse</h2><p className="mt-1 text-xs text-muted-foreground">A small daily read</p></div><Link href="/markets" className="grid h-8 w-8 place-items-center rounded-lg text-muted-foreground hover:bg-muted hover:text-primary" data-testid="link-market-pulse"><ChevronRight className="h-4 w-4" /></Link></div><div className="mt-5 space-y-1">{data.markets.map((market) => <div className="flex items-center justify-between border-b border-border/60 py-3 last:border-0" key={market.label} data-testid={`row-market-${market.label.replaceAll(' ', '-').toLowerCase()}`}><div className="text-xs font-bold">{market.label}</div><div className="flex items-center gap-3"><span className="font-mono text-xs">{market.value}</span><span className={`font-mono text-[10px] font-medium ${market.positive ? 'text-[#4b8b62]' : 'text-[#bc624d]'}`}>{market.change}</span></div></div>)}</div></div>
    </section>

    <section className="rounded-2xl border border-border bg-card p-5 md:p-6"><div className="flex items-center justify-between"><div><h2 className="text-base font-extrabold tracking-[-0.02em]">Recent activity</h2><p className="mt-1 text-xs text-muted-foreground">Your latest workspace actions</p></div><button onClick={() => toast.info('Activity filters are available from the full activity view.')} className="rounded-lg p-2 text-muted-foreground hover:bg-muted hover:text-foreground" data-testid="button-activity-menu"><MoreHorizontal className="h-4 w-4" /></button></div><div className="mt-5 grid gap-3 md:grid-cols-3">{data.activity.map((item, index) => <div className="flex gap-3 rounded-xl bg-muted/55 p-3.5" key={item.title} data-testid={`activity-${index}`}><div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-card text-primary shadow-sm">{item.type === 'analysis' ? <Sparkles className="h-3.5 w-3.5" /> : item.type === 'watch' ? <Star className="h-3.5 w-3.5" /> : <FileText className="h-3.5 w-3.5" />}</div><div><div className="text-xs font-bold">{item.title}</div><div className="mt-1 text-[10px] text-muted-foreground">{item.detail}</div><div className="mt-2 font-mono text-[9px] uppercase tracking-[0.1em] text-muted-foreground/75">{item.time}</div></div></div>)}</div></section>
  </div>;
}